CREATE TABLE IF NOT EXISTS `demoTable` (
  `demoID` int(11) NOT NULL AUTO_INCREMENT,
  `demoVarchar` varchar(36) DEFAULT NULL,
  `demoChar` char(16) DEFAULT NULL,
  `demoTimeStamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`demoID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
